package frontend;


import frontend.BorrowBook;
import frontend.AddBook;
import backend.Book;
import backend.LibrarianRole;
import backend.StudentBook;
import java.io.IOException;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sss
 */
public class librarianRole extends javax.swing.JFrame implements Node {
JFrame parent;
LibrarianRole librarian = new LibrarianRole();
private ViewBooks table;
private ViewBorrowedBooks table1;
    /**
     * Creates new form LibrarianRole
     */
    public librarianRole(JFrame parent)  throws IOException{
        initComponents();
        this.parent=parent;
        this.setTitle("Librarian Role");

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        view = new javax.swing.JButton();
        borrow = new javax.swing.JButton();
        v_borrow = new javax.swing.JButton();
        return1 = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Librarian Role");

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add Book");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(0, 0, 0));
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View Books");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        borrow.setBackground(new java.awt.Color(0, 0, 0));
        borrow.setForeground(new java.awt.Color(255, 255, 255));
        borrow.setText("Borrow Book");
        borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowActionPerformed(evt);
            }
        });

        v_borrow.setBackground(new java.awt.Color(0, 0, 0));
        v_borrow.setForeground(new java.awt.Color(255, 255, 255));
        v_borrow.setText("View Borrowed Books");
        v_borrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        v_borrow.setInheritsPopupMenu(true);
        v_borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_borrowActionPerformed(evt);
            }
        });

        return1.setBackground(new java.awt.Color(0, 0, 0));
        return1.setForeground(new java.awt.Color(255, 255, 255));
        return1.setText("Return Book");
        return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return1ActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(v_borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(return1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(v_borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(return1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
         this.setVisible(false);
         if(table==null)
         {table=new ViewBooks(new String[]{"Book Id","Title","Author","Publisher","no of copies"});
         }
         Book[] books= librarian.getListOfBooks();
         String[][] tabledata = new String[books.length][5];
         for(int i=0;i<books.length;i++)
         { tabledata[i]=books[i].lineRepresentation().split(",");
         }
         table.setData(tabledata);
         this.setVisible(false);
         table.setParentNode(this);
         table.setVisible(true);
    }//GEN-LAST:event_viewActionPerformed

    private void borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowActionPerformed
         BorrowBook b = new BorrowBook(this, librarian);
        this.setVisible(false);
        b.setParentNode(this);
        b.setVisible(true);
    }//GEN-LAST:event_borrowActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        parent.setVisible(true);
       this.setVisible(false);
       librarian.logout();
    }//GEN-LAST:event_logoutActionPerformed

    private void return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return1ActionPerformed
        ReturnBook b = new ReturnBook(this, librarian);
        this.setVisible(false);
        b.setParentNode(this);
        b.setVisible(true);
    }//GEN-LAST:event_return1ActionPerformed

    private void v_borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_borrowActionPerformed
              this.setVisible(false);
         if(table1==null)
         {table1=new ViewBorrowedBooks(new String[]{"Student Id","Book Id","Borrow Date"});
         }
         StudentBook[] sbooks= librarian.getListOfBorrowingOperations() ;
         String[][] tabledata = new String[sbooks.length][3];
         for(int i=0;i<sbooks.length;i++)
         { tabledata[i]=sbooks[i].lineRepresentation().split(",");
         }
         table1.setData(tabledata);
         this.setVisible(false);
         table1.setParentNode(this);
         table1.setVisible(true);
        
        
    }//GEN-LAST:event_v_borrowActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        AddBook b = new AddBook(this, librarian);
        this.setVisible(false);
        b.setParentNode(this);
        b.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton borrow;
    private javax.swing.JButton logout;
    private javax.swing.JButton return1;
    private javax.swing.JButton v_borrow;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setParentNode(Node node) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
